### ISSUE TITLE
Could not find global/templates/fs_xfms

### ISSUE THREAD

**Issue by XYWCQM** [Washington-University/NHPPipelines#2]
Hi:
   When I use the NHPPipelines to process my monkey data, encountered an error during FreeSurferPipelineNHP, the error content is unable to find "Macaque_rescale.xfm", I did not find "/ fs_xfms / Macaque_rescale" under the "$ {HCPPIPEDIR_Templates}" path. How can I solve this problem? Thank you.

**Comment by takuya-hayashi** [comment]
Sorry, now it was updated.
